<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
// quitar el id, y cambiar el estado, agregar el nombre municpio
    $municipio = Municipio::create(['municipio' => 'Abriaquí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Acacías', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Acandí', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Acevedo', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Achí', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Agrado', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Agua de Dios', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Aguachica', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Aguada', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Aguadas', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Aguazul', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Agustín Codazzi', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Aipe', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Albania', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Albania', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Albania', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Albán', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Albán', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Alcalá', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Alejandria', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Algarrobo', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Algeciras', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Almaguer', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Almeida', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Alpujarra', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Altamira', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Alto Baudó (Pie de Pato)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Altos del Rosario', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Alvarado', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Amagá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Amalfi', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Ambalema', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Anapoima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ancuya', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Andalucía', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Andes', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Angelópolis', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Angostura', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Anolaima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Anorí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Anserma', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Ansermanuevo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Anzoátegui', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Anzá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Apartadó', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Apulo', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Apía', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Aquitania', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Aracataca', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Aranzazu', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Aratoca', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Arauca', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Arauquita', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Arbeláez', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Arboleda (Berruecos)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Arboledas', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Arboletes', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Arcabuco', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Arenal', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Argelia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Argelia', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Argelia', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Ariguaní (El Difícil)', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Arjona', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Armenia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Armenia', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Armero (Guayabal)', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Arroyohondo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Astrea', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Ataco', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Atrato (Yuto)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Ayapel', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Bagadó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Bahía Solano (Mútis)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Bajo Baudó (Pizarro)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Balboa', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Balboa', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Baranoa', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Baraya', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Barbacoas', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Barbosa', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Barbosa', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Barichara', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Barranca de Upía', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Barrancabermeja', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Barrancas', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Barranco de Loba', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Barranquilla', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Becerríl', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Belalcázar', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Bello', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Belmira', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Beltrán', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Belén', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Belén', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Belén de Bajirá', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Belén de Umbría', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Belén de los Andaquíes', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Berbeo', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Betania', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Beteitiva', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Betulia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Betulia', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Bituima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Boavita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Bochalema', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Bogotá D.C.', 'departamento_id' => 11]);
	$municipio = Municipio::create(['municipio' => 'Bojacá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Bojayá (Bellavista)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Bolívar', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Bolívar', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Bolívar', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Bolívar', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Bosconia', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Boyacá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Briceño', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Briceño', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Bucaramanga', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Bucarasica', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Buenaventura', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Buenavista', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Buenavista', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Buenavista', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Buenavista', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Buenos Aires', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Buesaco', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Buga', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Bugalagrande', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Burítica', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Busbanza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cabrera', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Cabrera', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Cabuyaro', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Cachipay', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Caicedo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Caicedonia', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Caimito', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Cajamarca', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Cajibío', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Cajicá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Calamar', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Calamar', 'departamento_id' => 95, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'Calarcá', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Caldas', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Caldas', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Caldono', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'California', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Calima (Darién)', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Caloto', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Calí', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Campamento', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Campo de la Cruz', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Campoalegre', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Campohermoso', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Canalete', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Candelaria', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Candelaria', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Cantagallo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Cantón de San Pablo', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Caparrapí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Capitanejo', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Caracolí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Caramanta', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Carcasí', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Carepa', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Carmen de Apicalá', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Carmen de Carupa', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Carmen de Viboral', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Carmen del Darién (CURBARADÓ)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Carolina', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Cartagena', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Cartagena del Chairá', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Cartago', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Carurú', 'departamento_id' => 97]);
	$municipio = Municipio::create(['municipio' => 'Casabianca', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Castilla la Nueva', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Caucasia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Cañasgordas', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Cepita', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Cereté', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Cerinza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cerrito', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Cerro San Antonio', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Chachaguí', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Chaguaní', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Chalán', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Chaparral', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Charalá', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Charta', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Chigorodó', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Chima', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Chimichagua', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Chimá', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Chinavita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chinchiná', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Chinácota', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Chinú', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Chipaque', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Chipatá', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Chiquinquirá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chiriguaná', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Chiscas', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chitagá', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Chitaraque', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chivatá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chivolo', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Choachí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Chocontá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Chámeza', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Chía', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Chíquiza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Chívor', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cicuco', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Cimitarra', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Circasia', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Cisneros', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Ciénaga', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Ciénaga', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Ciénaga de Oro', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Clemencia', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Cocorná', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Coello', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Cogua', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Colombia', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Colosó (Ricaurte)', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Colón', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Colón (Génova)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Concepción', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Concepción', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Concordia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Concordia', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Condoto', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Confines', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Consaca', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Contadero', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Contratación', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Convención', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Copacabana', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Coper', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cordobá', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Corinto', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Coromoro', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Corozal', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Corrales', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cota', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Cotorra', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Covarachía', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Coveñas', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Coyaima', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Cravo Norte', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Cuaspud (Carlosama)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Cubarral', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Cubará', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cucaita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cucunubá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Cucutilla', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Cuitiva', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Cumaral', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Cumaribo', 'departamento_id' => 99]);
	$municipio = Municipio::create(['municipio' => 'Cumbal', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Cumbitara', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Cunday', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Curillo', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Curití', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Curumaní', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Cáceres', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Cáchira', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Cácota', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Cáqueza', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Cértegui', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Cómbita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Córdoba', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Córdoba', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Cúcuta', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Dabeiba', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Dagua', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Dibulla', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Distracción', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Dolores', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Don Matías', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Dos Quebradas', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Duitama', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Durania', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Ebéjico', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'El Bagre', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'El Banco', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'El Cairo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'El Calvario', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'El Carmen', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'El Carmen', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'El Carmen de Atrato', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'El Carmen de Bolívar', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'El Castillo', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'El Cerrito', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'El Charco', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'El Cocuy', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'El Colegio', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'El Copey', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'El Doncello', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'El Dorado', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'El Dovio', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'El Espino', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'El Guacamayo', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'El Guamo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'El Molino', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'El Paso', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'El Paujil', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'El Peñol', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'El Peñon', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'El Peñon', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'El Peñón', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'El Piñon', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'El Playón', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'El Retorno', 'departamento_id' => 95, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'El Retén', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'El Roble', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'El Rosal', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'El Rosario', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'El Tablón de Gómez', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'El Tambo', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'El Tambo', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'El Tarra', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'El Zulia', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'El Águila', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Elías', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Encino', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Enciso', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Entrerríos', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Envigado', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Espinal', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Facatativá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Falan', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Filadelfia', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Filandia', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Firavitoba', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Flandes', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Florencia', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Florencia', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Floresta', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Florida', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Floridablanca', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Florián', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Fonseca', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Fortúl', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Fosca', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Francisco Pizarro', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Fredonia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Fresno', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Frontino', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Fuente de Oro', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Fundación', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Funes', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Funza', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Fusagasugá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Fómeque', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Fúquene', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Gachalá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Gachancipá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Gachantivá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Gachetá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Galapa', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Galeras (Nueva Granada)', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Galán', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Gama', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Gamarra', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Garagoa', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Garzón', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Gigante', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Ginebra', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Giraldo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Girardot', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Girardota', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Girón', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Gonzalez', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Gramalote', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Granada', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Granada', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Granada', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Guaca', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Guacamayas', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Guacarí', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Guachavés', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Guachené', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Guachetá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guachucal', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Guadalupe', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Guadalupe', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Guadalupe', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Guaduas', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guaitarilla', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Gualmatán', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Guamal', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Guamal', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Guamo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Guapota', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Guapí', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Guaranda', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Guarne', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Guasca', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guatapé', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Guataquí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guatavita', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guateque', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Guavatá', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Guayabal de Siquima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guayabetal', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guayatá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Guepsa', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Guicán', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Gutiérrez', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Guática', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Gámbita', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Gámeza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Génova', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Gómez Plata', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Hacarí', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Hatillo de Loba', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Hato', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Hato Corozal', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Hatonuevo', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Heliconia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Herrán', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Herveo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Hispania', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Hobo', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Honda', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Ibagué', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Icononzo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Iles', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Imúes', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Inzá', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Inírida', 'departamento_id' => 94]);
	$municipio = Municipio::create(['municipio' => 'Ipiales', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Isnos', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Istmina', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Itagüí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Ituango', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Izá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Jambaló', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Jamundí', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Jardín', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Jenesano', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Jericó', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Jericó', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Jerusalén', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Jesús María', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Jordán', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Juan de Acosta', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Junín', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Juradó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'La Apartada y La Frontera', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'La Argentina', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'La Belleza', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'La Calera', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'La Capilla', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'La Ceja', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'La Celia', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'La Cruz', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'La Cumbre', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'La Dorada', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'La Esperanza', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'La Estrella', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'La Florida', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'La Gloria', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'La Jagua de Ibirico', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'La Jagua del Pilar', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'La Llanada', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'La Macarena', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'La Merced', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'La Mesa', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'La Montañita', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'La Palma', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'La Paz', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'La Paz (Robles)', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'La Peña', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'La Pintada', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'La Plata', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'La Playa', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'La Primavera', 'departamento_id' => 99]);
	$municipio = Municipio::create(['municipio' => 'La Salina', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'La Sierra', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'La Tebaida', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'La Tola', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'La Unión', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'La Unión', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'La Unión', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'La Unión', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'La Uvita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'La Vega', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'La Vega', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'La Victoria', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'La Victoria', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'La Victoria', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'La Virginia', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Labateca', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Labranzagrande', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Landázuri', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Lebrija', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Leiva', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Lejanías', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Lenguazaque', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Leticia', 'departamento_id' => 91]);
	$municipio = Municipio::create(['municipio' => 'Liborina', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Linares', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Lloró', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Lorica', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Los Córdobas', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Los Palmitos', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Los Patios', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Los Santos', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Lourdes', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Luruaco', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Lérida', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Líbano', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'López (Micay)', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Macanal', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Macaravita', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Maceo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Machetá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Madrid', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Magangué', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Magüi (Payán)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Mahates', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Maicao', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Majagual', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Malambo', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Mallama (Piedrancha)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Manatí', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Manaure', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Manaure Balcón del Cesar', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Manizales', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Manta', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Manzanares', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Maní', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Mapiripan', 'departamento_id' => 50, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'Margarita', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Marinilla', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Maripí', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Mariquita', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Marmato', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Marquetalia', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Marsella', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Marulanda', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'María la Baja', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Matanza', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Medellín', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Medina', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Medio Atrato', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Medio Baudó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Medio San Juan (ANDAGOYA)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Melgar', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Mercaderes', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Mesetas', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Milán', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Miraflores', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Miraflores', 'departamento_id' => 95, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'Miranda', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Mistrató', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Mitú', 'departamento_id' => 97]);
	$municipio = Municipio::create(['municipio' => 'Mocoa', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Mogotes', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Molagavita', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Momil', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Mompós', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Mongua', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Monguí', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Moniquirá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Montebello', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Montecristo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Montelíbano', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Montenegro', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Monteria', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Monterrey', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Morales', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Morales', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Morelia', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Morroa', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Mosquera', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Mosquera', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Motavita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Moñitos', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Murillo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Murindó', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Mutatá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Mutiscua', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Muzo', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Málaga', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Nariño', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Nariño', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Nariño', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Natagaima', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Nechí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Necoclí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Neira', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Neiva', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Nemocón', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Nilo', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Nimaima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Nobsa', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Nocaima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Norcasia', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Norosí', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Novita', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Nueva Granada', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Nuevo Colón', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Nunchía', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Nuquí', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Nátaga', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Obando', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Ocamonte', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Ocaña', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Oiba', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Oicatá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Olaya', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Olaya Herrera', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Onzaga', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Oporapa', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Orito', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Orocué', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Ortega', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Ospina', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Otanche', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Ovejas', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Pachavita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Pacho', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Padilla', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Paicol', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Pailitas', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Paime', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Paipa', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Pajarito', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Palermo', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Palestina', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Palestina', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Palmar', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Palmar de Varela', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Palmas del Socorro', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Palmira', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Palmito', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Palocabildo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Pamplona', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Pamplonita', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Pandi', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Panqueba', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Paratebueno', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Pasca', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Patía (El Bordo)', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Pauna', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Paya', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Paz de Ariporo', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Paz de Río', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Pedraza', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Pelaya', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Pensilvania', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Peque', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Pereira', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Pesca', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Peñol', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Piamonte', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Pie de Cuesta', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Piedras', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Piendamó', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Pijao', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Pijiño', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Pinchote', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Pinillos', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Piojo', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Pisva', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Pital', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Pitalito', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Pivijay', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Planadas', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Planeta Rica', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Plato', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Policarpa', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Polonuevo', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Ponedera', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Popayán', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Pore', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Potosí', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Pradera', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Prado', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Providencia', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Providencia', 'departamento_id' => 88]);
	$municipio = Municipio::create(['municipio' => 'Pueblo Bello', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Pueblo Nuevo', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Pueblo Rico', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Pueblorrico', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Puebloviejo', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Puente Nacional', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Puerres', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Puerto Asís', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Puerto Berrío', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Puerto Boyacá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Puerto Caicedo', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Puerto Carreño', 'departamento_id' => 99]);
	$municipio = Municipio::create(['municipio' => 'Puerto Colombia', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Puerto Concordia', 'departamento_id' => 50, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'Puerto Escondido', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Puerto Gaitán', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Puerto Guzmán', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Puerto Leguízamo', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Puerto Libertador', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Puerto Lleras', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Puerto López', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Puerto Nare', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Puerto Nariño', 'departamento_id' => 91]);
	$municipio = Municipio::create(['municipio' => 'Puerto Parra', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Puerto Rico', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Puerto Rico', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Puerto Rondón', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Puerto Salgar', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Puerto Santander', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Puerto Tejada', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Puerto Triunfo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Puerto Wilches', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Pulí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Pupiales', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Puracé (Coconuco)', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Purificación', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Purísima', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Pácora', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Páez', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Páez (Belalcazar)', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Páramo', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Quebradanegra', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Quetame', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Quibdó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Quimbaya', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Quinchía', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Quipama', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Quipile', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ragonvalia', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Ramiriquí', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Recetor', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Regidor', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Remedios', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Remolino', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Repelón', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Restrepo', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Restrepo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Retiro', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Ricaurte', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ricaurte', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Rio Negro', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Rioblanco', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Riofrío', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Riohacha', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Risaralda', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Rivera', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Roberto Payán', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Roldanillo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Roncesvalles', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Rondón', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Rosas', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Rovira', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Ráquira', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Río Iró', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Río Quito', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Río Sucio', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Río Viejo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Río de oro', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Ríonegro', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Ríosucio', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Sabana de Torres', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Sabanagrande', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Sabanalarga', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Sabanalarga', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Sabanalarga', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Sabanas de San Angel (SAN ANGEL)', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Sabaneta', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Saboyá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sahagún', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Saladoblanco', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Salamina', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Salamina', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Salazar', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Saldaña', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Salento', 'departamento_id' => 63]);
	$municipio = Municipio::create(['municipio' => 'Salgar', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Samacá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Samaniego', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Samaná', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Sampués', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Agustín', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'San Alberto', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'San Andrés', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San Andrés Sotavento', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San Andrés de Cuerquía', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Antero', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San Antonio', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'San Antonio de Tequendama', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'San Benito', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San Benito Abad', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Bernardo', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'San Bernardo', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'San Bernardo del Viento', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San Calixto', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'San Carlos', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Carlos', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San Carlos de Guaroa', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'San Cayetano', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'San Cayetano', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'San Cristobal', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Diego', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'San Eduardo', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San Estanislao', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Fernando', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Francisco', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Francisco', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'San Francisco', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'San Gíl', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San Jacinto', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Jacinto del Cauca', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Jerónimo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Joaquín', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San José', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'San José de Miranda', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San José de Montaña', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San José de Pare', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San José de Uré', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San José del Fragua', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'San José del Guaviare', 'departamento_id' => 95, 'status' => 1]);
	$municipio = Municipio::create(['municipio' => 'San José del Palmar', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Arama', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Betulia', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Nepomuceno', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Pasto', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Río Seco', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'San Juan de Urabá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Juan del Cesar', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'San Juanito', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'San Lorenzo', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'San Luis', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'San Luís', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Luís de Gaceno', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San Luís de Palenque', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'San Marcos', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Martín', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'San Martín', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'San Martín de Loba', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Mateo', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San Miguel', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San Miguel', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'San Miguel de Sema', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San Onofre', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Pablo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'San Pablo', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'San Pablo de Borbur', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'San Pedro', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Pedro', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'San Pedro', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'San Pedro de Cartago', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'San Pedro de Urabá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Pelayo', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'San Rafael', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Roque', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Sebastián', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'San Sebastián de Buenavista', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'San Vicente', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'San Vicente del Caguán', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'San Vicente del Chucurí', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'San Zenón', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Sandoná', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Santa Ana', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Santa Bárbara', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Santa Bárbara', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Santa Bárbara (Iscuandé)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Santa Bárbara de Pinto', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Santa Catalina', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Santa Fé de Antioquia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Santa Genoveva de Docorodó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Santa Helena del Opón', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Santa Isabel', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Santa Lucía', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Santa Marta', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Santa María', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Santa María', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa de Cabal', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa de Osos', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa de Viterbo', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosa del Sur', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Santa Rosalía', 'departamento_id' => 99]);
	$municipio = Municipio::create(['municipio' => 'Santa Sofía', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Santana', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Santander de Quilichao', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Santiago', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Santiago', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Santo Domingo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Santo Tomás', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Santuario', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Santuario', 'departamento_id' => 66]);
	$municipio = Municipio::create(['municipio' => 'Sapuyes', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Saravena', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Sardinata', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Sasaima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sativanorte', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sativasur', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Segovia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Sesquilé', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sevilla', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Siachoque', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sibaté', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sibundoy', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Silos', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Silvania', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Silvia', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Simacota', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Simijaca', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Simití', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Sincelejo', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Sincé', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Sipí', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Sitionuevo', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Soacha', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Soatá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Socha', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Socorro', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Socotá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sogamoso', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Solano', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Soledad', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Solita', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Somondoco', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sonsón', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Sopetrán', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Soplaviento', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Sopó', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sora', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Soracá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sotaquirá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sotara (Paispamba)', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Sotomayor (Los Andes)', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Suaita', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Suan', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Suaza', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Subachoque', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sucre', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Sucre', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Sucre', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Suesca', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Supatá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Supía', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Suratá', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Susa', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Susacón', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sutamarchán', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Sutatausa', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Sutatenza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Suárez', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Suárez', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Sácama', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Sáchica', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tabio', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tadó', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Talaigua Nuevo', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Tamalameque', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Tame', 'departamento_id' => 81]);
	$municipio = Municipio::create(['municipio' => 'Taminango', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Tangua', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Taraira', 'departamento_id' => 97]);
	$municipio = Municipio::create(['municipio' => 'Tarazá', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Tarqui', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Tarso', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Tasco', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tauramena', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Tausa', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tello', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Tena', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tenerife', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Tenjo', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tenza', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Teorama', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Teruel', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Tesalia', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Tibacuy', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tibaná', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tibasosa', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tibirita', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tibú', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Tierralta', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Timaná', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Timbiquí', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Timbío', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Tinjacá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tipacoque', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tiquisio (Puerto Rico)', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Titiribí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Toca', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tocaima', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Tocancipá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Toguí', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Toledo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Toledo', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Tolú', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Tolú Viejo', 'departamento_id' => 70]);
	$municipio = Municipio::create(['municipio' => 'Tona', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Topagá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Topaipí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Toribío', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Toro', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Tota', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Totoró', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Trinidad', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Trujillo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Tubará', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Tuchín', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Tulúa', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Tumaco', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Tunja', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tunungua', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Turbaco', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Turbaná', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Turbo', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Turmequé', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tuta', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Tutasá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Támara', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Támesis', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Túquerres', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Ubalá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ubaque', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ubaté', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ulloa', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Une', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Unguía', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Unión Panamericana (ÁNIMAS)', 'departamento_id' => 27]);
	$municipio = Municipio::create(['municipio' => 'Uramita', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Uribe', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Uribia', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Urrao', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Urumita', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Usiacuri', 'departamento_id' => 8]);
	$municipio = Municipio::create(['municipio' => 'Valdivia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Valencia', 'departamento_id' => 23]);
	$municipio = Municipio::create(['municipio' => 'Valle de San José', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Valle de San Juan', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Valle del Guamuez', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Valledupar', 'departamento_id' => 20]);
	$municipio = Municipio::create(['municipio' => 'Valparaiso', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Valparaiso', 'departamento_id' => 18]);
	$municipio = Municipio::create(['municipio' => 'Vegachí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Venadillo', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Venecia', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Venecia (Ospina Pérez)', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Ventaquemada', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Vergara', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Versalles', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Vetas', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Viani', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Vigía del Fuerte', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Vijes', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Villa Caro', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Villa Rica', 'departamento_id' => 19]);
	$municipio = Municipio::create(['municipio' => 'Villa de Leiva', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Villa del Rosario', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Villagarzón', 'departamento_id' => 86]);
	$municipio = Municipio::create(['municipio' => 'Villagómez', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Villahermosa', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Villamaría', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Villanueva', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Villanueva', 'departamento_id' => 44]);
	$municipio = Municipio::create(['municipio' => 'Villanueva', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Villanueva', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Villapinzón', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Villarrica', 'departamento_id' => 73]);
	$municipio = Municipio::create(['municipio' => 'Villavicencio', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Villavieja', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Villeta', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Viotá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Viracachá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Vista Hermosa', 'departamento_id' => 50]);
	$municipio = Municipio::create(['municipio' => 'Viterbo', 'departamento_id' => 17]);
	$municipio = Municipio::create(['municipio' => 'Vélez', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Yacopí', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Yacuanquer', 'departamento_id' => 52]);
	$municipio = Municipio::create(['municipio' => 'Yaguará', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Yalí', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Yarumal', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Yolombó', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Yondó (Casabe)', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Yopal', 'departamento_id' => 85]);
	$municipio = Municipio::create(['municipio' => 'Yotoco', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Yumbo', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Zambrano', 'departamento_id' => 13]);
	$municipio = Municipio::create(['municipio' => 'Zapatoca', 'departamento_id' => 68]);
	$municipio = Municipio::create(['municipio' => 'Zapayán (PUNTA DE PIEDRAS)', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Zaragoza', 'departamento_id' => 5]);
	$municipio = Municipio::create(['municipio' => 'Zarzal', 'departamento_id' => 76]);
	$municipio = Municipio::create(['municipio' => 'Zetaquirá', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Zipacón', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Zipaquirá', 'departamento_id' => 25]);
	$municipio = Municipio::create(['municipio' => 'Zona Bananera (PRADO - SEVILLA)', 'departamento_id' => 47]);
	$municipio = Municipio::create(['municipio' => 'Ábrego', 'departamento_id' => 54]);
	$municipio = Municipio::create(['municipio' => 'Íquira', 'departamento_id' => 41]);
	$municipio = Municipio::create(['municipio' => 'Úmbita', 'departamento_id' => 15]);
	$municipio = Municipio::create(['municipio' => 'Útica', 'departamento_id' => 25]);

    }
}
