import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: {
                // CSS files
                'app_css': 'resources/css/app.css',
                'style': 'resources/css/style.css',
                'temas_css': 'resources/css/temas.css',
                'parametros_css': 'resources/css/parametros.css',
                'aitg_planes_contratacion_css': 'resources/css/aitg/planes-contratacion/app.css',
                'programas_css': 'resources/css/programas.css',
                'programas_publicos_css': 'resources/css/programas_publicos.css',
                'aprendices_css': 'resources/css/aprendices.css',
                'instructores_css': 'resources/css/instructores.css',
                'guias_aprendizaje_css': 'resources/css/guias-aprendizaje.css',
                'resultados_aprendizaje_css': 'resources/css/resultados-aprendizaje.css',
                'dias_formacion_css': 'resources/css/dias-formacion.css',
                'fichas_css': 'resources/css/fichas.css',
                'competencias_css': 'resources/css/competencias.css',
                'red_conocimiento_css': 'resources/css/red-conocimiento.css',
                'livewire_loading_css': 'resources/css/livewire-loading.css',
                'global_notifications_css': 'resources/css/global-notifications.css',
                'global_modals_css': 'resources/css/global-modals.css',
                'footer_css': 'resources/css/footer.css',
                'registro_css': 'resources/css/pages/registro.css',
                'dashboard_superadmin': 'resources/css/dashboards/dashboard-superadmin.css',
                'caracter_selecter': 'resources/css/Asistencia/caracter_selecter.css',
                'index_qr_css': 'resources/css/Asistencia/index_qr.css',
                // Inventario CSS files
                'inventario_base_css': 'resources/css/inventario/shared/base.css',
                'inventario_card_css': 'resources/css/inventario/card.css',
                'inventario_carrito_css': 'resources/css/inventario/carrito.css',
                'inventario_imagen_css': 'resources/css/inventario/imagen.css',
                'inventario_inventario_css': 'resources/css/inventario/inventario.css',
                'inventario_modal_orden_css': 'resources/css/inventario/modal-orden.css',
                'inventario_modal_producto_css': 'resources/css/inventario/modal-producto.css',
                'inventario_notificaciones_css': 'resources/css/inventario/notificaciones.css',
                'inventario_orden_css': 'resources/css/inventario/orden.css',
                'inventario_email_css': 'resources/css/inventario/email.css',
                // Complementarios CSS files
                'formulario_inscripcion_css': 'resources/css/formulario_inscripcion.css',
                'gestion_aspirantes_css': 'resources/css/complementario/gestion_aspirantes.css',
                'ver_aspirantes_css': 'resources/css/complementario/ver_aspirantes.css',
                'procesar_documentos_css': 'resources/css/complementario/procesar_documentos.css',
                // 'navbar': 'resources/css/shared/navbar.css',
                // JavaScript files - Root
                'app': 'resources/js/app.js',
                'aprendices': 'resources/js/aprendices.js',
                'bootstrap': 'resources/js/bootstrap.js',
                'dashboard': 'resources/js/dashboard.js',
                'debug-permissions': 'resources/js/debug-permissions.js',
                'echo-config': 'resources/js/echo-config.js',
                'global_modals': 'resources/js/global-modals.js',
                'global_notifications': 'resources/js/global-notifications.js',
                'guias-aprendizaje': 'resources/js/guias-aprendizaje.js',
                'logout': 'resources/js/logout.js',
                'municipios': 'resources/js/municipios.js',
                'parametros': 'resources/js/parametros.js',
                'aitg_plan_contratacion_form': 'resources/js/aitg/planes-contratacion/index.js',
                'aitg_spa': 'resources/js/aitg/spa.js',
                'red-conocimiento': 'resources/js/red-conocimiento.js',
                'tema': 'resources/js/tema.js',
                // Asistencia files
                'asistencia_index_qr': 'resources/js/Asistencia/index-qr.js',
                // Dashboards files
                'charts-scripts': 'resources/js/dashboards/superadmin/charts-scripts.js',
                'widgets': 'resources/js/dashboards/superadmin/widgets.js',
                // Inventario files
                'inventario_aprobaciones': 'resources/js/inventario/aprobaciones.js',
                'inventario_card': 'resources/js/inventario/card.js',
                'inventario_carrito': 'resources/js/inventario/carrito.js',
                'inventario_escaner': 'resources/js/inventario/escaner.js',
                'inventario_fecha_vencimiento': 'resources/js/inventario/fecha-vencimiento.js',
                'inventario_filtro_departamento': 'resources/js/inventario/filtro-departamento.js',
                'inventario_global': 'resources/js/inventario/global.js',
                'inventario_imagen': 'resources/js/inventario/imagen.js',
                'inventario_notificaciones': 'resources/js/inventario/notificaciones.js',
                'inventario_solicitud': 'resources/js/inventario/solicitud.js',
                'inventario_select-marca': 'resources/js/inventario/select-marca.js',
                'inventario_ordenes_index': 'resources/js/inventario/ordenes-index.js',
                // Complementarios files
                'estadisticas_complementarios': 'resources/js/complementarios/estadisticas.js',
                'aspirantes_programa': 'resources/js/complementarios/aspirantes/programa.js',
                'complementarios_dias_horarios': 'resources/js/complementarios/dias-horarios.js',
                'complementarios_formulario_inscripcion': 'resources/js/complementarios/formulario-inscripcion.js',
                // Modules files
                'alert-handler': 'resources/js/modules/alert-handler.js',
                'bulk-actions': 'resources/js/modules/bulk-actions.js',
                'confirm-delete-modal': 'resources/js/modules/confirm-delete-modal.js',
                'form-handler': 'resources/js/modules/form-handler.js',
                'fullscreen-remember': 'resources/js/modules/fullscreen-remember.js',
                'historial-asignaciones': 'resources/js/modules/historial-asignaciones.js',
                'livewire-logout-fix': 'resources/js/modules/livewire-logout-fix.js',
                'preloader': 'resources/js/modules/preloader.js',
                'select-dinamico': 'resources/js/modules/select-dinamico.js',
                'sidebar-persist': 'resources/js/modules/sidebar-persist.js',
                'storage-safe': 'resources/js/modules/storage-safe.js',
                'table-actions': 'resources/js/modules/table-actions.js',
                'tracking-prevention-suppress': 'resources/js/modules/tracking-prevention-suppress.js',
                // Pages files
                'aprendices_index': 'resources/js/pages/aprendices-index.js',
                'competencias_form': 'resources/js/pages/competencias-form.js',
                'competencias_index': 'resources/js/pages/competencias-index.js',
                'detalle-generico': 'resources/js/pages/detalle-generico.js',
                'fichas-form': 'resources/js/pages/fichas-form.js',
                'fichas-index': 'resources/js/pages/fichas-index.js',
                'formularios-generico': 'resources/js/pages/formularios-generico.js',
                'formularios-select-dinamico': 'resources/js/pages/formularios-select-dinamico.js',
                'gestion-especializada': 'resources/js/pages/gestion-especializada.js',
                'guias-aprendizaje-form': 'resources/js/pages/guias-aprendizaje-form.js',
                'guias-aprendizaje-index': 'resources/js/pages/guias-aprendizaje-index.js',
                'instructores-dashboard': 'resources/js/pages/instructores-dashboard.js',
                'instructores-edit': 'resources/js/pages/instructores-edit.js',
                'instructores-fichas-asignadas': 'resources/js/pages/instructores-fichas-asignadas.js',
                'instructores-gestionar-especialidades': 'resources/js/pages/instructores-gestionar-especialidades.js',
                'instructores-index-moderno': 'resources/js/pages/instructores-index-moderno.js',
                'instructores_index': 'resources/js/pages/instructores-index.js',
                'instructores-show': 'resources/js/pages/instructores-show.js',
                'permisos': 'resources/js/pages/permisos.js',
                'personas': 'resources/js/pages/personas.js',
                'programas-index': 'resources/js/pages/programas-index.js',
                'red-conocimiento-index': 'resources/js/pages/red-conocimiento-index.js',
                'registro-actividades-form': 'resources/js/pages/registro-actividades-form.js',
                'registro-actividades-index': 'resources/js/pages/registro-actividades-index.js',
                'resultados_aprendizaje_index': 'resources/js/pages/resultados-aprendizaje-index.js',
                'table-page': 'resources/js/pages/table-page.js',
                // Personas files
                'personas-form': 'resources/js/personas/form.js',
            },
            refresh: true,
        }),
    ],
    server: {
        host: '0.0.0.0',  // Escucha en todas las interfaces de red
        port: 5173,
        strictPort: true,
        watch: {
            ignored: [
                /(^|[/\\])vendor([/\\]|$)/,
                /(^|[/\\])storage([/\\]|$)/,
                /(^|[/\\])bootstrap[/\\]cache([/\\]|$)/,
                /(^|[/\\])routes([/\\]|$)/,
                /(^|[/\\])database([/\\]|$)/,
                /(^|[/\\])public([/\\]|$)/,
            ],
        },
        hmr: {
            host: 'localhost',  // Usa localhost para HMR en el navegador
        },
    },
});
